FROM ubuntu
RUN apt update
RUN apt install openjdk-11-jdk -y
ENV JAVA_HOME /usr
ADD apache-tomcat-10.1.42.tar.gz /opt
COPY target/gamutkart.war /opt/apache-tomcat-10.1.42/webapps
ENTRYPOINT ["/opt/apache-tomcat-10.1.42/bin/catalina.sh", "run"]

